[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
zayden-core = { git = "https://github.com/zayden-bot/slash-command-core.git", branch = "master" }
lfg = { git = "https://github.com/zayden-bot/lfg.git", branch = "main" }
temp-voice = { git = "https://github.com/zayden-bot/temp-voice.git", branch = "main" }
ticket = { git = "https://github.com/zayden-bot/ticket.git", branch = "main" }
suggestions = { git = "https://github.com/zayden-bot/suggestions.git", branch = "main" }
levels = { git = "https://github.com/zayden-bot/levels.git", branch = "main" }
async-trait = { version = "*", default-features = false }
dotenvy = { version = "*", default-features = false }
tokio = { version = "*", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
chrono = { version = "*", default-features = false }
rand = { version = "*", default-features = false }
chrono-tz = { version = "*", default-features = false }
sqlx = { version = "*", default-features = false, features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "macros",
    "chrono",
    "uuid",
] }
serenity = { version = "*", default-features = false, features = [
    "builder",
    "client",
    "collector",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
] }
const_format = { version = "*", default-features = false }
