pub const SPACES: [&str; 76] = [
    "Mentions how long the transition is",
    "Brad Falls off the map",
    "Brad dies in transition",
    "Brad spends 2+ mins in a plate room",
    "Gives up & asks to be sherpa'd",
    "Finds secret chest room",
    "Dies to darkness energy columns",
    "10+ minutes spent on a transition",
    "Team does not use Friendship door",
    "Door closes on someone",
    "2 mins to start after friendship door",
    "Team can't find the plate",
    "Wipe to time after 1st rotation",
    "Someone dies to supplicants",
    "Team misses a hydra",
    "Dies in the boss arena during mechanic",
    "Brad misses bounce from being frozen",
    "Misses a blight",
    "Wipes in the final room",
    "Dies to turrets or complains about them",
    "Wipes due to early pillar close",
    "Brad dunks in the wrong statue",
    "Brad can't remember people's ghosts",
    "Realizes statue is themself",
    "Brad mentions how bright it is ",
    "Brad thinks he died during ghost phase",
    "Brad visibly rages because of Verity",
    "3+ die to Witness attack during DPS",
    "Tries to t-crash the Witness",
    "Fails the Witness test",
    "Brad dies to Witness attack",
    "Brad gets suspended",
    "Calls something \"bad ass\"",
    "Forgets to dunk resonance at any point ",
    "Dies to resonance timer",
    "Finds a collectable ",
    "Dies to a hand",
    "Smokes a crayon",
    "\"OH I GET IT\"",
    "\"This is easy\"",
    "Dodge IRL",
    "Brad wears glasses",
    "Team blames bug/glitch",
    "Accidentally starts encounter early",
    "Chat claims \"not blind\"",
    "Failed a final stand",
    "Brad wears the wig",
    "Queens breaker used",
    "Lord of Wolves used",
    "\"Clean dick\" is said",
    "Brad throws something across the room",
    "Someone blows themselves up",
    "Completes the encounter without a hint",
    "Misses a t-crash",
    "Voice crack",
    "Brad orders food",
    "\"Yeah, this is gonna be a LOOOONG raid\"",
    "Gets sherpa'd",
    "Someone disconnects or has to leave",
    "Mentions raid or Witness is massive",
    "Complains about ads",
    "Dies from too many resonances",
    "Vents with workout or hits 'assistant'",
    "Says he might need to take a break ",
    "Not enough resonance dunk for max time",
    "Gets an energy drink/coffee",
    "\"Wipe it\", is said ",
    "Jokes about needing a college degree",
    "Says: \"Easy once you know it\"",
    "Reads subs, chat or dono mid fight",
    "Reference to the music being good or bad",
    "Doesn't know what loadout to use",
    "Brad slides down in his seat in despair",
    "Brad spawns a supplicant",
    "Someone dies to the resonance timer",
    "Wipes due to closing with wrong shape",
];
